---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: **********
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
 name: login
 labels:
   app: login
data:
 DB_LOGIN: cG9zdGdyZXM=
type: Opaque


---
apiVersion: v1
kind: Secret
metadata:
 name: password
 labels:
   app: password
data:
 DB_PASSWORD: MXEydzNlOTk=
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
 name: db-secret
 labels:
   app: generate-short-links
data:
 dbname: cG9zdGdyZXM=
 password: MXEydzNlOTk=
 username: cG9zdGdyZXM=
type: Opaque
