---
apiVersion: v1
kind: Service
metadata:
   name: postgres
   labels:
     app: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      protocol: TCP
      targetPort: {{ .Values.db.port }}
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: generate-short-links
  labels:
    app: generate-short-links
    chart: "generate-short-links-{{ .Chart.Version }}"
spec:
  selector:
    app: generate-short-links
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
