---
image:
  repository: "repo_url"
  tag: 1.0.1650764

replicas: 1
javaopts:
  - "-Xms200M"
  - "-Xmx500M"
  - "-XX:+UseG1GC"
  - "-XX:+UseStringDeduplication"
  - "-XX:+UseCompressedOops"
  - "-XX:+HeapDumpOnOutOfMemoryError"
  - "-XX:HeapDumpPath=/tmp/heapdump.hprof"
  - "-XX:+PrintGCDetails"
  - "-XX:+PrintCommandLineFlags"
  - "-XX:+UnlockExperimentalVMOptions"
  - "-XX:MaxRAMFraction=1"
  - "-XX:+ExitOnOutOfMemoryError"
  - "-XX:+UseContainerSupport"
  - "-XX:NativeMemoryTracking=summary" 

db:
  host: "postgres"
  port: 5432

devmode:
  enabled: true

resources:
  requests:
    cpu: 0.3
    memory: 200Mi
  limits:
    cpu: 0.5
    memory: 500Mi


service:
  type: ClusterIP
  port: 80
  targetport: 80     